'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class AdministratorPlant
    
    '''<summary>
    '''upnl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnl As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblPlants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlants As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownListPlant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListPlant As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblBusinessUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBusinessUnit As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownListBusinessUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListBusinessUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblPlatform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlatform As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownListPlatform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListPlatform As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblProductionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductionType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownListProductionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownListProductionType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''DivProductionLines control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivProductionLines As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblProductionLineOrArea control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductionLineOrArea As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxProductionLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxProductionLine As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtProductionLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductionLine As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddProductionLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddProductionLine As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnDeleteProductionLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteProductionLine As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnRefreshProductionLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRefreshProductionLine As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''DivDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivDepartments As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lbldepartment control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbldepartment As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxDepartments As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDepartments As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ButtonAddDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddDepartments As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ButtonDeleteDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDeleteDepartments As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ButtonRefreshDepartments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonRefreshDepartments As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''DivCBN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DivCBN As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblCBN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCBN As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxCNB control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxCNB As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtCBN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCBN As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ButtonAddCBN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonAddCBN As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ButtonDeleteCBN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonDeleteCBN As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ButtonRefreshCBN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ButtonRefreshCBN As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''CheckBoxEnableAuto control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents CheckBoxEnableAuto As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''divEnableDisable control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEnableDisable As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''txtDirectory control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDirectory As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''RadioButtonUseCorporate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonUseCorporate As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''RadioButtonSingleSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents RadioButtonSingleSource As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''txtSingleSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSingleSource As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''files control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents files As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fuGsumSmallWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuGsumSmallWS As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbls control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbls As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblfuGsumSmallWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfuGsumSmallWS As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''lblGsumSmallWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGsumSmallWS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtGsumSmallWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGsumSmallWS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCellGsumSmallWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCellGsumSmallWS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCellGsumSmallWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCellGsumSmallWS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Div1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fuGSUMMTL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuGSUMMTL As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbl_file_fuGSUMMTL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_file_fuGSUMMTL As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Div9 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div9 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblfuGSUMMTL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfuGSUMMTL As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGSUMMTL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGSUMMTL As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtGSUMMTL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGSUMMTL As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCellGSUMMTL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCellGSUMMTL As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCellGSUMMTL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCellGSUMMTL As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Div2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div2 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fuGSUMPRWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuGSUMPRWS As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbl_file_fuGSUMPRWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_file_fuGSUMPRWS As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Div10 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div10 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblfuGSUMPRWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfuGSUMPRWS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGSUMPRWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGSUMPRWS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtGSUMPRWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGSUMPRWS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCellGSUMPRWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCellGSUMPRWS As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCellGSUMPRWS control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCellGSUMPRWS As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Div3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div3 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fuGSUMMFGOps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuGSUMMFGOps As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbl_file_fuGSUMMFGOps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_file_fuGSUMMFGOps As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Div11 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div11 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblfuGSUMMFGOps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfuGSUMMFGOps As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGSUMMFGOps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGSUMMFGOps As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtGSUMMFGOps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGSUMMFGOps As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCellGSUMMFGOps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCellGSUMMFGOps As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCellGSUMMFGOps control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCellGSUMMFGOps As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Div4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div4 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fuMFGDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuMFGDel As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbl_file_fuMFGDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_file_fuMFGDel As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Div12 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div12 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblfuMFGDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfuMFGDel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblMFGDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMFGDel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtMFGDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMFGDel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCellMFGDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCellMFGDel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCellMFGDel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCellMFGDel As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Div5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div5 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fuEWPTracker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuEWPTracker As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbl_file_fuEWPTracker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_file_fuEWPTracker As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Div13 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div13 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblfuEWPTracker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfuEWPTracker As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblEWPTracker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblEWPTracker As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtEWPTracker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEWPTracker As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCellEWPTracker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCellEWPTracker As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCellEWPTracker control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCellEWPTracker As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Div6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div6 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fuGSUM_IAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuGSUM_IAP As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbl_file_fuGSUM_IAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_file_fuGSUM_IAP As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Div14 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div14 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblfuGSUM_IAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfuGSUM_IAP As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGSUM_IAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGSUM_IAP As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtGSUM_IAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGSUM_IAP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCellGSUM_IAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCellGSUM_IAP As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCellGSUM_IAP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCellGSUM_IAP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Div7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div7 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fuRE_Implementation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuRE_Implementation As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbl_file_fuRE_Implementation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_file_fuRE_Implementation As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Div15 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div15 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblfuRE_Implementation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfuRE_Implementation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblRE_Implementation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRE_Implementation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtRE_Implementation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRE_Implementation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCellRE_Implementation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCellRE_Implementation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCellRE_Implementation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCellRE_Implementation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''Div8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div8 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''fuGSUM_PRRA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuGSUM_PRRA As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lbl_file_fuGSUM_PRRA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbl_file_fuGSUM_PRRA As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''Div16 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Div16 As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''lblfuGSUM_PRRA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblfuGSUM_PRRA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lblGSUM_PRRA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblGSUM_PRRA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtGSUM_PRRA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtGSUM_PRRA As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblcellGSUM_PRRA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblcellGSUM_PRRA As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCellGSUM_PRRA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCellGSUM_PRRA As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnSaveSource control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSaveSource As Global.System.Web.UI.WebControls.Button
End Class
