'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Admin_Project
    
    '''<summary>
    '''upnl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnl As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''chkAdvancedMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAdvancedMode As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''btnSerach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSerach As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''chkSrch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkSrch As Global.System.Web.UI.WebControls.CheckBox
    
    '''<summary>
    '''divSrchExist control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divSrchExist As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DdlPlants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlPlants As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlSrchProjectType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSrchProjectType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlSrchChangeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSrchChangeType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlSrchBusinessUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSrchBusinessUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''ddlSrchProductionLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlSrchProductionLine As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''BtnSrchExistingStartup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSrchExistingStartup As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''gdvSrch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents gdvSrch As Global.System.Web.UI.WebControls.GridView
    
    '''<summary>
    '''DdlPlantsInsert control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlPlantsInsert As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''txtstartupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtstartupName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''txtProjectName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProjectName As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''rbYes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbYes As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rbNo control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbNo As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''DdlCOmplexityofStartup control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlCOmplexityofStartup As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''rbCustom control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbCustom As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rbSmall control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbSmall As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''rbLarge control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents rbLarge As Global.System.Web.UI.WebControls.RadioButton
    
    '''<summary>
    '''cblGSUM control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblGSUM As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''cblEWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblEWP As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''cblREImplementationPlan control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents cblREImplementationPlan As Global.System.Web.UI.WebControls.CheckBoxList
    
    '''<summary>
    '''spanltoCBN control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanltoCBN As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spanltoPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanltoPriority As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DdlProjectType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlProjectType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlChangeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlChangeType As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlLinktoCBn control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlLinktoCBn As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlPriority control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlPriority As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''spanimpactDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanimpactDept As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spanleadingDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanleadingDept As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DdlBusinessUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlBusinessUnit As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlProductionLine control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlProductionLine As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlImpactDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlImpactDept As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlLeadingDept control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlLeadingDept As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''spansulCoach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spansulCoach As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spansnSiel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spansnSiel As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''spanprjMgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents spanprjMgr As Global.System.Web.UI.HtmlControls.HtmlGenericControl
    
    '''<summary>
    '''DdlSUL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlSUL As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlSULCoach control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlSULCoach As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlSNSIEL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlSNSIEL As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''DdlPrjMgr control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DdlPrjMgr As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''btnRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefresh As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnCoachRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCoachRefresh As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnSNSIELRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSNSIELRefresh As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnPrjMgrRefresh control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrjMgrRefresh As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnSetTargetsandMilestones control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSetTargetsandMilestones As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnSave control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSave As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''btnMileStone control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnMileStone As Global.System.Web.UI.WebControls.Button
End Class
