'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Dashboard
    
    '''<summary>
    '''BtnEditMeasures control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEditMeasures As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnCreatePorject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnCreatePorject As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnEditPractitioners control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnEditPractitioners As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnAdminforPlant control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAdminforPlant As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''trGlobal_Admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trGlobal_Admin As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''trBtnGlobal_Admin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents trBtnGlobal_Admin As Global.System.Web.UI.HtmlControls.HtmlTableRow
    
    '''<summary>
    '''BtnAdmin control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAdmin As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''BtnSet control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnSet As Global.System.Web.UI.WebControls.Button
    
    '''<summary>
    '''DDlplants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DDlplants As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''BtnReports control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnReports As Global.System.Web.UI.WebControls.Button
End Class
