'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class GlobalAdmin
    
    '''<summary>
    '''upnl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnl As Global.System.Web.UI.UpdatePanel
    
    '''<summary>
    '''lblProductionTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProductionTypes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxProductionType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxProductionType As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtProductionTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProductionTypes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddProductionTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddProductionTypes As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnDeleteProductionTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteProductionTypes As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnRefreshProductionTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefreshProductionTypes As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblProjectTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblProjectTypes As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxprojType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxprojType As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtprojectType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtprojectType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnaddtxtprojectType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnaddtxtprojectType As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnDeletetxtprojectType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeletetxtprojectType As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnRefreshtxtprojectType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefreshtxtprojectType As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblChangeType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblChangeType As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxChangType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxChangType As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtChangType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtChangType As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddChangType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddChangType As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnDeleteChangType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteChangType As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnRefreshChangType control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRefreshChangType As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblBusinessUnits control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBusinessUnits As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxBusinUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxBusinUnit As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtBusinUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtBusinUnit As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddBusinUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddBusinUnit As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnDeleteBusinUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDeleteBusinUnit As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnRefreshBusinUnit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRefreshBusinUnit As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Image1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image1 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblPlatform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlatform As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxPlatform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxPlatform As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtPlatform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPlatform As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnAddPlatform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAddPlatform As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnDeletePlatform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDeletePlatform As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnRefreshPlatform control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefreshPlatform As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''PlantsLBL control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents PlantsLBL As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''DropDownlblPlantsAssociateBU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents DropDownlblPlantsAssociateBU As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblSwp control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSwp As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxSWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxSWP As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtSWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSWP As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnAddSWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAddSWP As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnDeleteSWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDeleteSWP As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnRefreshSWP control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRefreshSWP As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Image2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image2 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblPracticionerRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPracticionerRole As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxPracticionerRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxPracticionerRole As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtPracticionerRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPracticionerRole As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddPracticionerRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPracticionerRole As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnDeletePracticionerRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeletePracticionerRole As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnRefreshPracticionerRole control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRefreshPracticionerRole As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblSWP_Tool_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSWP_Tool_Name As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lbSWP_Tool_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbSWP_Tool_Name As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtSWP_Tool_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSWP_Tool_Name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddSWP_Tool_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddSWP_Tool_Name As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnDeleteSWP_Tool_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteSWP_Tool_Name As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnRefreshSWP_Tool_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefreshSWP_Tool_Name As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Image4 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image4 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblCorporate_WS_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorporate_WS_Name As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCorporate_WS_Name control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorporate_WS_Name As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCorporate_Cell_Location_For_Score control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorporate_Cell_Location_For_Score As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''txtCorporate_Cell_Location_For_Score control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtCorporate_Cell_Location_For_Score As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''lblCorporate_Tool_Source_LOcation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCorporate_Tool_Source_LOcation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''lnkbtnFileName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lnkbtnFileName As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnEdit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnEdit As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.LinkButton
    
    '''<summary>
    '''fuCorporate_Standard_File control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents fuCorporate_Standard_File As Global.System.Web.UI.WebControls.FileUpload
    
    '''<summary>
    '''lblComplexitySituation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblComplexitySituation As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxComplexitySituation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxComplexitySituation As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtComplexitySituation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtComplexitySituation As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''BtnAddComplexitySituation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnAddComplexitySituation As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnDeleteComplexitySituation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDeleteComplexitySituation As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnRefreshComplexitySituation control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRefreshComplexitySituation As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Image5 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image5 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblPracticionerRoleID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPracticionerRoleID As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlPracticionerRoleID control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPracticionerRoleID As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Image6 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image6 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblPSQualificationLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPSQualificationLevel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlPSQualificationLevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlPSQualificationLevel As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''lblqulaificationlevel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblqulaificationlevel As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxQualificationTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxQualificationTypes As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtQualificationTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtQualificationTypes As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddQualificationTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddQualificationTypes As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnDeletequalificationTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeletequalificationTypes As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnRefreshQualificationTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefreshQualificationTypes As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Label1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label1 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBox1 As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''TextBox1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents TextBox1 As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''ImageButton1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton1 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ImageButton2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton2 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''ImageButton3 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ImageButton3 As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Label2 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Label2 As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxRegions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxRegions As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtRegions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtRegions As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddRegions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddRegions As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnDeleteRegions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteRegions As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''btnRefreshRegions control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefreshRegions As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''lblPlants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlants As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ListBoxPlants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ListBoxPlants As Global.System.Web.UI.WebControls.ListBox
    
    '''<summary>
    '''txtPalnts control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPalnts As Global.System.Web.UI.WebControls.TextBox
    
    '''<summary>
    '''btnAddPlants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddPlants As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnDeletePlants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnDeletePlants As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''BtnRefreshPlants control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents BtnRefreshPlants As Global.System.Web.UI.WebControls.ImageButton
    
    '''<summary>
    '''Image7 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image7 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblRegion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblRegion As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlRegionTypes control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlRegionTypes As Global.System.Web.UI.WebControls.DropDownList
    
    '''<summary>
    '''Image8 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Image8 As Global.System.Web.UI.WebControls.Image
    
    '''<summary>
    '''lblBU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblBU As Global.System.Web.UI.WebControls.Label
    
    '''<summary>
    '''ddlBU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlBU As Global.System.Web.UI.WebControls.DropDownList
End Class
