'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Startupstargets

    '''<summary>
    '''upnl control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents upnl As Global.System.Web.UI.UpdatePanel

    '''<summary>
    '''chkAdvancedMode control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkAdvancedMode As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lbltxtProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lbltxtProject As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtProject As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnSearch control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSearch As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''lblStartupName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStartupName As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlStartUpName control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStartUpName As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divStartupStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divStartupStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblStartUpStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblStartUpStatus As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''ddlStartUpStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents ddlStartUpStatus As Global.System.Web.UI.WebControls.DropDownList

    '''<summary>
    '''divCharacterApproved control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divCharacterApproved As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblCharacter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblCharacter As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkCharacter control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkCharacter As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblPlantAE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPlantAE As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''chkPlantAE control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents chkPlantAE As Global.System.Web.UI.WebControls.CheckBox

    '''<summary>
    '''lblSAPProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblSAPProject As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtSAPProject control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtSAPProject As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divEtcTargetStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divEtcTargetStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblETCTarger control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblETCTarger As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtETCTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtETCTarget As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''diPrTargetStatus control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents diPrTargetStatus As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblPRTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblPRTarget As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtPRTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPRTarget As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''hr1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents hr1 As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMilestoneTarget control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMilestoneTarget As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtMlstnFeasibility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMlstnFeasibility As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMlstnConceptual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMlstnConceptual As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divtxtMlstnPCStrategy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divtxtMlstnPCStrategy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtMlstnPCStrategy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMlstnPCStrategy As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMlstnProjectFSF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMlstnProjectFSF As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divtxtMlstnStartupWorkProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divtxtMlstnStartupWorkProcess As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtMlstnStartupWorkProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMlstnStartupWorkProcess As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''divtxtMlstnStartupProduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divtxtMlstnStartupProduction As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''txtMlstnStartupProduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMlstnStartupProduction As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMlstnSustain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMlstnSustain As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMlstnPSU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMlstnPSU As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMlstnG2TDay1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMlstnG2TDay1 As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMlstnG2TConstructionCompletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMlstnG2TConstructionCompletion As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMlstnG2TEndofPQPhase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMlstnG2TEndofPQPhase As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtMlstnG2T_End_of_Ininital_Verification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtMlstnG2T_End_of_Ininital_Verification As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lblMlstnFeasibility control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMlstnFeasibility As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMlstnConceptual control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMlstnConceptual As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divMlstnPCStrategy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMlstnPCStrategy As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMlstnPCStrategy control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMlstnPCStrategy As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMlstnProjectFSF control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMlstnProjectFSF As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divMlstnStartupWorkProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divMlstnStartupWorkProcess As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMlstnStartupWorkProcess control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMlstnStartupWorkProcess As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''divlblMlstnStartupProduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents divlblMlstnStartupProduction As Global.System.Web.UI.HtmlControls.HtmlGenericControl

    '''<summary>
    '''lblMlstnStartupProduction control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMlstnStartupProduction As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMlstnSustain control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMlstnSustain As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMlstnPSU control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMlstnPSU As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMlstnG2TDay1 control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMlstnG2TDay1 As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMlstnG2TConstructionCompletion control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMlstnG2TConstructionCompletion As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMlstnG2TEndofPQPhase control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMlstnG2TEndofPQPhase As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''lblMlstnG2T_End_of_Ininital_Verification control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lblMlstnG2T_End_of_Ininital_Verification As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''txtEODate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtEODate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtDays As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lstboxEODate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstboxEODate As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnRefreshEODate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefreshEODate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnAddEODate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddEODate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnDeleteEODate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteEODate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtConstructionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConstructionDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtConstructionDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtConstructionDays As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lstboxConstructionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstboxConstructionDate As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnRefreshConstructionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefreshConstructionDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnAddConstructionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddConstructionDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnDeleteConstructionDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteConstructionDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtVatDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVatDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''txtVatDays control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtVatDays As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''lstboxVATDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents lstboxVATDate As Global.System.Web.UI.WebControls.ListBox

    '''<summary>
    '''btnRefreshVatDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnRefreshVatDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnAddVatDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnAddVatDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''btnDeleteVatDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnDeleteVatDate As Global.System.Web.UI.WebControls.ImageButton

    '''<summary>
    '''txtcomments control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtcomments As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnback control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnback As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnCancel control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnCancel As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnSubmit control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnSubmit As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnApprovedPCA control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnApprovedPCA As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''btnPrev control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnPrev As Global.System.Web.UI.WebControls.Button

    '''<summary>
    '''txtPCAApprovedDate control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents txtPCAApprovedDate As Global.System.Web.UI.WebControls.TextBox

    '''<summary>
    '''btnNext control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents btnNext As Global.System.Web.UI.WebControls.Button
End Class
